---
- hosts: webservers
  gather_facts: yes
  tasks:
    - name: Update repositories cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Installing nginx
      become: yes
      apt:
        name: nginx
        state: latest
    - name: Installing php7.4-fpm
      become: yes
      apt:
        name: php7.4-fpm
        state: present
    - name: Copying index.php file
      become: yes
      copy:
        src: index.php
        dest: /var/www/html/
    - name: Uploading Nginx configuration file
      become: yes
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
    - name: Enabling configuration file
      become: yes
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: Starting a Web Server
      become: yes
      service:
        name: nginx
        state: started
- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
    - name: Upadating repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
    - name: uploading haproxy configuration file
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    - name: Reinitializing HAProxy
      service:
        name: haproxy
        state: restarted
