---
- hosts: webservers
  gather_facts: yes
  become: yes
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Installing Python3-pip 
      apt:
         name: python3-pip
         state: present
         
    - name: Install flask for Python3 using the 'pip3' executable
      ansible.builtin.pip:
        name: flask
        executable: pip3
        state: latest

    - name: Upload the application to the servers
      copy:
        src: ./service.py
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Run the application
      shell: python3 /home/ubuntu/service.py
      async: 86400
      poll: 0
      
    - name: Install the snmpdaemon
      apt:
              name: snmpd
              state: latest
    
    - name: Copy the snmpd config file
      ansible.builtin.copy:
              src: ./snmpd.conf
              dest: /etc/snmp/snmpd.conf

    - name: Run the snmpdaemon
      service:
              name: snmpd
              state: restarted 

- hosts: proxyserver
  gather_facts: yes
  become: yes
  tasks:
    - name: Upadating repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installing NGINX 
      apt:
        name: nginx
        state: present

    - name: uploading NGINX configuration file
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restarting NGINX
      service:
        name: nginx
        state: restarted